name: Build and Deploy
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Build App
      run: npm run build
      env:
        REACT_APP_MV_FIREBASE_API_KEY: ${{ secrets.REACT_APP_MV_FIREBASE_API_KEY }}
        REACT_APP_MV_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_MV_FIREBASE_AUTH_DOMAIN }}
        REACT_APP_MV_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_MV_FIREBASE_PROJECT_ID }}
        REACT_APP_MV_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_MV_FIREBASE_STORAGE_BUCKET }}
        REACT_APP_MV_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MV_FIREBASE_MESSAGING_SENDER_ID }}
        REACT_APP_MV_FIREBASE_APP_ID: ${{ secrets.REACT_APP_MV_FIREBASE_APP_ID }}
        REACT_APP_MV_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_MV_FIREBASE_MEASUREMENT_ID }}

    # add further steps for deploying your app here
